language: c

env:
 matrix:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

compiler:
 - clang
 - gcc

sudo: false

addons:
 apt:
  sources:
   - kalakris-cmake
  pacakges:
   - cmake
   - lcov
   - libgsl0-dev
   - python

install:
 - apt-get update && apt-get upgrade -yy
 - git submodule update --init
 - mkdir build
 - mkdir target
 - cd build

script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=$BUILD_TYPE
 - make
 - python ../tests/axe_cli_tests.py  .
 - ./bin/test_axe
 - make install
 - test -f ../target/bin/axe-demux
