language: c

env:
 matrix:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

compiler:
 - clang
 - gcc

sudo: false

addons:
 apt:
  sources:
   - kalakris-cmake
  packages:
   - cmake
   - lcov
   - libgsl0-dev
   - python
   - python-sphinx

install:
 - pushd $HOME
 - wget http://zlib.net/zlib-1.2.8.tar.xz
 - tar xvf zlib-1.2.8.tar.xz
 - cd zlib-1.2.8
 - ./configure --prefix=$HOME
 - make
 - make install
 - popd
 - git submodule update --init
 - mkdir build
 - mkdir target
 - cd build

script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DZLIB_ROOT=$HOME
 - make
 - python ../tests/axe_cli_tests.py  .
 - ./bin/test_axe
 - make install
 - test -f ../target/bin/axe-demux
