language: c

env:
 matrix:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

compiler:
 - clang
 - gcc

before_install:
 - sudo add-apt-repository --yes ppa:kalakris/cmake
 - sudo apt-get update -qq
 - sudo apt-get install --yes cmake
 - sudo apt-get update
 - sudo apt-get install lcov python-pip valgrind libgsl0-dev
 - mkdir zlib && cd zlib
 - wget http://zlib.net/zlib-1.2.8.tar.gz
 - tar xvxf zlib-1.2.8.tar.gz
 - cd zlib-1.2.8
 - ./configure
 - make
 - sudo make install
 - cd ../..

install:
 - git submodule update --init
 - mkdir build
 - mkdir target
 - cd build

script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=$BUILD_TYPE
 - make
 - python ../tests/axe_cli_tests.py  .
 - ./bin/test_axe
 - make install
 - test -f ../target/bin/axe-demux
